### ISSUE TITLE
subscribe for more than one event

### ISSUE THREAD

**Issue by vijay543** [seanpar203/event-bus#2]
Subscribe a function for more than one event.('event string   in this case')...is this possible.

Thanks,

**Comment by seanpar203** [comment]
Sure there is the `add_event` method on the `EventBus` class which allows you to manually add functions to specific events. Look at the codebase below to see how you can achieve using the same function for multiple events.

```py
from event_bus import EventBus

bus = EventBus()

def func(str_to_print):
    print(str_to_print)

EVENT_ONE = 'print_str'
EVENT_TWO = 'str_print'

if __name__ == '__main__':
    bus.add_event(func, EVENT_ONE)
    bus.add_event(func, EVENT_TWO)

    bus.emit(EVENT_ONE, 'Printing from func')
    bus.emit(EVENT_TWO, 'Printing from func')
```
